# Prometheus Configuration for Sidecar Pattern
# Scrapes metrics from localhost (other containers in the same instance)

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'oci-container-sidecar'
    environment: 'production'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          type: 'monitoring'

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8080']
        labels:
          exporter: 'cadvisor'
          service: 'container-metrics'

  # Node Exporter - Host metrics
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9100']
        labels:
          exporter: 'node-exporter'
          service: 'host-metrics'

  # Application metrics (if exposed)
  - job_name: 'application'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:8081']  # Application metrics port
        labels:
          exporter: 'application'
          service: 'app-metrics'

  # Nginx Exporter (optional)
  - job_name: 'nginx'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9113']
        labels:
          exporter: 'nginx'
          service: 'nginx-metrics'

  # Redis Exporter (optional)
  - job_name: 'redis'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9121']
        labels:
          exporter: 'redis'
          service: 'redis-metrics'

  # PostgreSQL Exporter (optional)
  - job_name: 'postgres'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9187']
        labels:
          exporter: 'postgres'
          service: 'postgres-metrics'

  # MySQL Exporter (optional)
  - job_name: 'mysql'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9104']
        labels:
          exporter: 'mysql'
          service: 'mysql-metrics'

  # Blackbox Exporter (optional)
  - job_name: 'blackbox'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9115']
        labels:
          exporter: 'blackbox'
          service: 'endpoint-probing'

# Remote write disabled - Management Agent will scrape from Prometheus /metrics endpoint
# This avoids connection refused errors when Management Agent is not yet running
# remote_write:
#   - url: http://localhost:9091/api/v1/push  # If using push gateway
#     queue_config:
#       capacity: 10000
#       max_shards: 5
#       min_shards: 1
#       max_samples_per_send: 5000
#       batch_send_deadline: 5s
#       min_backoff: 30ms
#       max_backoff: 100ms
